ダミーデータを追加
Mokumoku-Rin/RinRinRun pull request #123
Opened 2020-03-10 05:56 UTC by kibehiro

とりあえず作ったけどほんまにこれでええんか……？
KIBEは訝しんだ

2020-03-10 07:39 UTC, hiragi-gkuth requested changes
多分ID周りで既にあるデータと整合性ズレそう。
ダミーデータ全部100番からにしませんか。

2020-03-10 07:56 UTC, kibehiro commented
あい！

2020-03-10 12:51 UTC, hiragi-gkuth requested changes
おーん

2020-03-10 12:51 UTC, HiragiGKUTH commented on db/migration/33-landmarks.sql
> +('100', '高槻駅北行き',default,'https://files.slack.com/files-pri/TU8F7E2JC-FV2UT4DEU/ios__________.jpg','135.576238, 34.879169');
カンマの後にスペースはなしで

2020-03-10 12:51 UTC, HiragiGKUTH commented on db/migration/32-courses.sql
> +(`id`, `name`, `mean_distance`, `mean_time`, `played_count`)
一個目に100を振ったら次からは勝手に101...ってなっていく
ただ，ダミーデータを入れる上でわかりにくくなるなら残してもいいかも

2020-03-10 12:51 UTC, HiragiGKUTH commented on db/migration/34-landmark_visits.sql
> +INSERT INTO `landmark_visits` (`id`, `workout_history_id`, `landmark_id`, `time`)
timeはそれぞれの間の値ではなく，開始時間からの経過時間になると思われる(要出典)
それだと，これらの値だと辻褄が合わん

2020-03-10 12:54 UTC, kibehiro commented on db/migration/34-landmark_visits.sql
> +INSERT INTO `landmark_visits` (`id`, `workout_history_id`, `landmark_id`, `time`)
はえ～

2020-03-10 12:54 UTC, kibehiro commented on db/migration/33-landmarks.sql
> +('100', '高槻駅北行き',default,'https://files.slack.com/files-pri/TU8F7E2JC-FV2UT4DEU/ios__________.jpg','135.576238, 34.879169');
おk
それはそうとなんでなんや？

2020-03-10 12:55 UTC, kibehiro commented on db/migration/32-courses.sql
> +(`id`, `name`, `mean_distance`, `mean_time`, `played_count`)
個人的には明示したほうがいいかなと思うので、とりあえず残しまする

2020-03-10 13:31 UTC, HiragiGKUTH commented on db/migration/33-landmarks.sql
> +('100', '高槻駅北行き',default,'https://files.slack.com/files-pri/TU8F7E2JC-FV2UT4DEU/ios__________.jpg','135.576238, 34.879169');
文字列を ","で分割しているので，そのときにスペースが残ると不具合が起きるかもしれんからとりあえずなしの方向になっている．
そもそも文字列データで持つべきかって話もあって結局まとまっていない．明日まとめたい

2020-03-10 13:36 UTC, kibehiro commented on db/migration/33-landmarks.sql
> +('100', '高槻駅北行き',default,'https://files.slack.com/files-pri/TU8F7E2JC-FV2UT4DEU/ios__________.jpg','135.576238, 34.879169');
はえ～

2020-03-11 03:14 UTC, hiragi-gkuth approved these changes
とりあえずLGTM
なんかバグったら修正を別で投げよう

2020-03-11 03:14 UTC, merged