一応の一通りの画面遷移
Mokumoku-Rin/RinRinRun pull request #153
Opened 2020-03-12 12:30 UTC by myabu-dev

画面遷移が一応完成しました
いろいろエラーとかデザインが崩れています
デザインの方は修正がよくわからんのでマージしてから直す方向で

サーバー側のエラーもマージしてから直す方向で

2020-03-12 12:32 UTC, myabu-dev commented
カメラ撮る時にオーバーレイが出たり出なかったりするのは仕様です←は？
データはあるのでCSSの問題なんだと思うけどよくわからん

2020-03-12 12:33 UTC, myabu-dev commented
@kibehiro 
いちおうこのブランチなら、画像送信できる

2020-03-12 12:34 UTC, myabu-dev commented
HOMEからちゃんと遷移しないとエラー出るので、手順通りやってください

2020-03-12 12:35 UTC, myabu-dev commented
.envに
VUE_APP_API_ENDPOINT = http://localhost:8081
を加えないと動かないわ...

2020-03-13 03:49 UTC, HiragiGKUTH commented
@myabu-dev 
それ，別ブランチで対応したのでこのブランチにマージして

2020-03-13 03:54 UTC, kibehiro reviewed
ざっと見た感じこんなもん
Request changesするほどでもないと思うので、Commentにとどめておく

2020-03-13 03:54 UTC, kibehiro commented on client/src/src/views/RunningGoal.vue
> +    distance += dist
共通化できそうと思ったけどちょっとだけ違うのかぁ……

2020-03-13 03:54 UTC, kibehiro commented on client/src/src/views/RunnningInfo.vue
> +      myLocation: SOJO_GPS_POSITION,
これなんでSOJO_GPS_POSITIONなんだっけ（痴呆）

2020-03-13 03:54 UTC, kibehiro commented on client/src/src/views/RunnningInfo.vue
> +            this.page_info.active_button = true
こいつ見るの2回目な気がするけど、共通化めんどい感じですか

2020-03-13 03:54 UTC, kibehiro commented on client/src/src/views/RunnningInfo.vue
> +    distance += dist
またこれか壊れるなぁ……

2020-03-13 03:54 UTC, kibehiro commented on client/src/src/views/TakePicture.vue
> +        img_url: '#'
これ'#'な意味あるの？

2020-03-13 04:01 UTC, hiragi-gkuth requested changes
なんか似たような処理が複数あるゾ，わｋらん
処理ができているならOKします

2020-03-13 04:01 UTC, hiragi-gkuth commented on client/src/src/components/CameraView.vue
> +      if(landmark.id  == this.landmarkID){
=== のほうが安全

2020-03-13 04:01 UTC, hiragi-gkuth commented on client/src/src/components/CameraView.vue
> +    setupVideo: async function(){
async functionなので，呼び出し元がawaitでないと動かない．
setupVideoを普通のfunctionにして，中のgetVideoStreamをcallbackの方にしないと多分動かなかったり動いたりする．

2020-03-13 04:01 UTC, hiragi-gkuth commented on client/src/src/components/RinRinMap.vue
> +          for(let index = 0; index < ghost.time_list.length; index++){
同一名の変数ってバグらんのか？
バグらんとしてもかなり読みにくいので，少し名前を工夫したほうが良さそう:thinking_face:

2020-03-14 04:43 UTC, myabu-dev commented on client/src/src/views/RunningGoal.vue
> +    distance += dist
これ本当は共通化するべき

2020-03-14 04:43 UTC, myabu-dev commented on client/src/src/views/RunningGoal.vue
> +    distance += dist
issueたてとく

2020-03-14 04:46 UTC, myabu-dev commented on client/src/src/views/RunnningInfo.vue
> +      myLocation: SOJO_GPS_POSITION,
初期座標のため
GPSの座標が取得されるまでのあいだ表示される座標

2020-03-14 04:46 UTC, myabu-dev commented on client/src/src/views/RunnningInfo.vue
> +            this.page_info.active_button = true
共通化した方がいいです...

2020-03-14 04:47 UTC, myabu-dev commented on client/src/src/views/TakePicture.vue
> +        img_url: '#'
意味はない

2020-03-14 04:47 UTC, myabu-dev commented on client/src/src/components/CameraView.vue
> +      if(landmark.id  == this.landmarkID){
これ、int型とstring型で型変換めんどくさいからこうなってる
ちゃんとphaseIntするかぁ

2020-03-14 04:48 UTC, myabu-dev commented on client/src/src/components/RinRinMap.vue
> +          for(let index = 0; index < ghost.time_list.length; index++){
バグらないけど、バグらせる可能性は上がるので変数名かえます

2020-03-14 07:18 UTC, myabu-dev commented on client/src/src/components/CameraView.vue
> +    setupVideo: async function(){
とりあえず前に戻した

2020-03-14 07:33 UTC, myabu-dev commented
@HiragiGKUTH 
取り合えず、指摘されていたとこはなおした
マージするブランチ
https://github.com/Mokumoku-Rin/RinRinRun/pull/157
であってた？

2020-03-15 01:58 UTC, HiragiGKUTH commented on client/src/src/components/CameraView.vue
> +      if(landmark.id  == this.landmarkID){
ecma2017なら，Number(variable)で行けるぞ

2020-03-15 01:59 UTC, HiragiGKUTH commented
@myabu-dev ほい，lgtmですが，マージ先はどちらでもOK

2020-03-15 02:01 UTC, HiragiGKUTH commented
@myabu-dev conflict直してマージ

2020-03-15 02:49 UTC, hiragi-gkuth approved these changes
lgtm わすれてた

2020-03-15 05:22 UTC, merged