生SQLでユーザーデータがインサートされるように
Mokumoku-Rin/RinRinRun pull request #47
Opened 2020-03-04 09:04 UTC by kibehiro

設計が終わりすぎる

2020-03-04 11:21 UTC, hiragi-gkuth requested changes
一応確認よろしく，設計思想を正しく表明できてないのが問題だったので，自分も同時に考える

2020-03-04 11:21 UTC, HiragiGKUTH commented on server/src/api/usecases/connectiondb.py
> +import pymysql.cursors
dbへのコネクションはusecasesではないかなぁと思う．
考えどころ．

2020-03-04 11:21 UTC, HiragiGKUTH commented on server/src/api/db/register.py
> +import pymysql.cursors
こっちはusecaseだと思う．
「ユーザが登録されているか」とか，「ユーザを登録する」アプリケーションを構成するロジックそのものなので，

get_db_connectionは「データベースに接続する」なので，サーバ都合

2020-03-04 11:21 UTC, HiragiGKUTH commented on server/src/api/db/register.py
> +    conn.commit()
なぜget_db_connectionがあるのにconnectionを受け取っているのだろう？:thinking_face:

2020-03-04 11:21 UTC, HiragiGKUTH commented on server/src/api/usecases/connectiondb.py
> +    return conn
この関数，例えば各場所から呼ばれたとき，その都度connectionを確立しようとするので，とても無駄な気がする．
同一リクエストにおいてはコネクションを使い回すか，あるいはサーバ自体でコネクションを持ち続ける設計のほうがよさそう．
その方法に関しては調べる

2020-03-04 11:46 UTC, kibehiro reviewed
設計なんもわかってなくてすまんな

2020-03-04 11:46 UTC, kibehiro commented on server/src/api/db/register.py
> +    conn.commit()
コネクションの使い回しのつもりですね
get_db_connectionの設計が終わりなので……
connectionが使い回せる設計にすればいらない

2020-03-04 11:46 UTC, kibehiro commented on server/src/api/usecases/connectiondb.py
> +    return conn
サーバー自体でコネクションの使い回し、Flaskならグローバル変数的に保つってのがあるんだけど、Fast APIだと軽く調べた感じみつからんかった 😢 
https://qiita.com/mtitg/items/47770e9a562dd150631d
https://shinyorke.hatenablog.com/entry/fastapi
このへん見るとやっぱりコネクションの使いまわしっぽい？

2020-03-04 11:46 UTC, kibehiro commented on server/src/api/usecases/connectiondb.py
> +import pymysql.cursors
🤔

2020-03-04 11:46 UTC, kibehiro commented on server/src/api/db/register.py
> +import pymysql.cursors
そう言われるとこのロジックがdbにあるのはおかしい気がしますね……
DBへの操作と登録有無のロジックは分けるべきやね(という認識であってるのかな？)

2020-03-04 13:32 UTC, kibehiro reviewed
とりあえず役割を見直してみた
なおDBとの接続維持

2020-03-04 13:43 UTC, HiragiGKUTH commented
@kibehiro 
接続維持に関してはすでに設計と実装を終わらした．バグ残ってるので修正する．
明日つづきやる

2020-03-04 13:51 UTC, hiragi-gkuth reviewed
一応追加確認

2020-03-04 13:51 UTC, HiragiGKUTH commented on server/src/api/db/user.py
> +def register_user(uid):
registerだと，登録という意味が載ってしまうのでinsert_userのほうが良さそう．
そして，insert_userを呼び出すのが /usecases/user.pyの中の register_user っぽいイメージ
あとは今後必要に合わせて update_user delete_userを実装していく想定

2020-03-04 14:39 UTC, HiragiGKUTH commented
結局今日やってしまったので，暇な人はレビューよろ

@kibehiro @myabu-dev

2020-03-04 14:54 UTC, HiragiGKUTH commented
#39 の結論がこれ

2020-03-04 15:59 UTC, kibehiro reviewed
俺の答えはこれや！
L　G　T　M

2020-03-05 00:05 UTC, hiragi-gkuth approved these changes
lgtm

2020-03-05 00:08 UTC, merged